### ISSUE TITLE
Firebase Deployment

### ISSUE THREAD

**Issue by hffmnn** [Canner/canner-firebase-cms#17]
The tutorial at https://www.canner.io/docs/tutorial-community-firebase.html describes a deployment to Firebase, but it looks like this got removed (https://github.com/Canner/canner-firebase-cms/commit/ab8f9e7beb9b0272e95e36dc18e61395fc0961c2). 

Is there any information why that happened? Or are there any plans to reenable it?

**Comment by abz53378** [comment]
Hi, @hffmnn, sorry about the late response. In ab8f9e7 , we change to use [nextJS](https://nextjs.org/docs/)(a framework for server-side react app) to build the CMS and [now](https://zeit.co/now) to deploy it because we were trying to implement SSR feature in our CMS.

For the example without NextJS, we are going to create a new [repo](https://github.com/Canner/canner-firestore-cms), you can watch and follow there.

**Comment by hffmnn** [comment]
Hi, thanks for the info. Will have a look a the repo.

**Comment by chilijung** [comment]
@hffmnn done! you can check out https://github.com/Canner/canner-firestore-cms
